---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-operator-config
  namespace: rocketmq-operator
  labels:
    app: rocketmq-operator
    release: "0.1.1"
data:
  operator-config.yaml: |
    #namespace: rocketmq-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-operator
  namespace: rocketmq-operator
  labels:
    release: "0.1.1"
    app: rocketmq-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-operator
  template:
    metadata:
      labels:
        app: rocketmq-operator
    spec:
      serviceAccountName: rocketmq-operator
      nodeSelector:
        rocketmq-operator: "on"
      volumes:
        - name: rocketmq-operator-config-volume
          configMap:
            name: rocketmq-operator-config
      containers:
      - name: rocketmq-operator-controller
        imagePullPolicy: Always
        image: huanwei/rocketmq-operator:0.1.1
        ports:
        - containerPort: 10254
        volumeMounts:
        - name: rocketmq-operator-config-volume
          mountPath: /etc/rocketmq-operator
        args:
          - --v=4
          - --namespace=rocketmq-operator
