#!/bin/bash

#BROKER_CONFIG_FILE="/opt/rocketmq-$ROCKETMQ_VERSION/conf/broker.conf"
BROKER_CONFIG_FILE=`pwd`/broker.conf
echo $BROKER_CONFIG_FILE

#--config begin
#BROKER_CLUSTER_NAME=DefaultCluster
#BROKER_NAME=broker-0
#BROKER_ID=0
#DELETE_WHEN=04
#FILE_RESERVED_TIME=48
#BROKER_ROLE=ASYNC_MASTER
#FLUSH_DISK_TYPE=ASYNC_FLUSH
#--config end

#BROKER_ID=$(cat /etc/hostname | grep -o '[^-]*$')
BROKER_ID=2
REPLICATION_MODE="ASYNC"

BROKER_ROLE="SLAVE"

if [ $BROKER_ID = 0 ];then
    if [ $REPLICATION_MODE = "SYNC" ];then
      BROKER_ROLE="SYNC_MASTER"
    else
      BROKER_ROLE="ASYNC_MASTER"
    fi
fi

function create_config() {
    rm -f $BROKER_CONFIG_FILE
    echo "Creating broker configuration."
    echo "#This file was auto generated by rocketmq-operator. DO NOT EDIT." >> $BROKER_CONFIG_FILE
    echo "brokerClusterName=$BROKER_CLUSTER_NAME" >> $BROKER_CONFIG_FILE
    echo "brokerName=$BROKER_NAME" >> $BROKER_CONFIG_FILE
    echo "brokerId=$BROKER_ID" >> $BROKER_CONFIG_FILE
    echo "deleteWhen=$DELETE_WHEN" >> $BROKER_CONFIG_FILE
    echo "fileReservedTime=$FILE_RESERVED_TIME" >> $BROKER_CONFIG_FILE
    echo "brokerRole=$BROKER_ROLE" >> $BROKER_CONFIG_FILE
    echo "flushDiskType=$FLUSH_DISK_TYPE" >> $BROKER_CONFIG_FILE
    echo "Wrote broker configuration file to $BROKER_CONFIG_FILE"
}


create_config


